# Base configs
baseurl: /profileflat

# UI configs
title: "Mufaddal Vanwala"
author: "Mufaddal Vanwala"
about: "An Achiever | A Dreamer | A Coder"
social_urls:
  facebook: "https://www.facebook.com/mufaddalvanwala"
  twitter: "https://www.twitter.com/muffvan"
  instagram: "https://www.instagram.com/m4muff"
  github: "https://github.com/muffvan"
